//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzasSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costumer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Costumer()
        {
            this.OrderTbs = new HashSet<OrderTb>();
        }
    
        public int CostumerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Addresss { get; set; }
        public string City { get; set; }
        public string TelNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTb> OrderTbs { get; set; }
    }
}
