//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzasSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTb
    {
        public int OrderId { get; set; }
        public int PizzaId { get; set; }
        public int ClientId { get; set; }
        public int AdminId { get; set; }
        public int Qty { get; set; }
        public float Price { get; set; }
        public string Payment { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Costumer Costumer { get; set; }
        public virtual Pizza Pizza { get; set; }
    }
}
